#!/usr/bin/expect -f

# Expect script. Expect Reference: https://linux.die.net/man/1/expect

set EXP_TMP tests/input
catch {set EXP_TMP $env(TEMPDIR)}

set EXP_CONFIG config
catch {set EXP_CONFIG $env(CONFIGDIR)}

set COLS [exec tput cols]
set LINE [exec bash -c "printf '=%.0s' {1..$COLS}"]

set timeout 10

# Cleanup previous runs
spawn rm -f $EXP_TMP/trigger-1 $EXP_TMP/trigger-2
expect eof

# Get version
spawn foremon --version
expect eof

# Start Test 1

# will trigger test2 later
spawn bash -c "
    sleep 4
    if touch $EXP_TMP/EXPECT_TEST2; then
        echo `date +%s` - OK - Set trigger $EXP_TMP/EXPECT_TEST2
    else
        echo `date +%s` - FAIL - Trigger was not set
    fi
"
expect_after {
    eof
}

spawn foremon -V -f $EXP_CONFIG/sanity-check.toml -a test1 -a test2
expect_after eof {
    send_user "\n$LINE\n"
    send_user "[exec date +%s] - DONE - SUCCESS\n"
    exit 0
}

send_user "\n$LINE\n"
send_user "[exec date +%s] - WORKING - Waiting for initial tasks to execute ...\n"
expect "starting"
expect "clean exit"
expect "clean exit" {
    send_user "\n$LINE\n"
    send_user "[exec date +%s] - WORKING - Sending RESTART\n"
    send "rs\n"
}

send_user "\n$LINE\n"
send_user "[exec date +%s] - WORKING - Waiting for restarted tasks to execute ...\n"
expect "starting"
expect "trigger*"
expect "clean exit*"
expect "starting"
expect "trigger*"
expect "clean exit*"

send_user "\n$LINE\n"
send_user "[exec date +%s] - WORKING - Waiting for file change event ...\n"
expect {
    "timeout" {
        send_user "\n$LINE\n"
        send_user "[exec date +%s] - FAIL - While waiting for filesystem event to fire\n\n"
        exit 1
    }

    "*EXPECT_TEST2 was modified"
}
expect "starting*"
expect "trigger-2"

expect "clean exit*" {
    send_user "\n$LINE\n"
    send_user "[exec date +%s] - WORKING - Sending exit command ...\n"
    send "exit\n"
    expect "stopping..."

    "timeout" {
        send_user "\n$LINE\n"
        send_user "[exec date +%s] - FAIL - foremon did not behave as expected\n"
        exit 1
    }
}

expect EOF
