name: CI

on:
  push:
    branches:
      - master
      - prerelease
    tags:
      - '**'
  pull_request: {}

jobs:
  test-linux:
    name: test py${{ matrix.os }} on linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [ "ubuntu-py36",
                "ubuntu-py37",
                "ubuntu-py38",
                "ubuntu-py39"]
        include:
          - name: "ubuntu-py36"
            python: "3.6"
            os: ubuntu-latest
            tox_env: "py36"
          - name: "ubuntu-py37"
            python: "3.7"
            os: ubuntu-latest
            tox_env: "py37"
          - python: "3.8"
            os: ubuntu-latest
            tox_env: "py38"
          - name: "ubuntu-py39"
            python: "3.9"
            os: ubuntu-latest
            tox_env: "py39-xdist"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install tox coverage

    - name: Test with coverage
      run: "tox -e ${{ matrix.tox_env }}"
